### ISSUE TITLE
implementation of whey

### ISSUE THREAD

**Issue by LQNew** [walegahaha/Curls-Whey#1]
thx for releasing your code, but I have a question that in your paper, Whey Optimization is to divide noises into groups, I read your code roughly, I think your whey implementation is to divide into groups by pixel values 0 - 255, do I understand correctly?And I don't find the T1 pram settings. By the way, your whey step2, squeeze noises stochastically, I don't find the implementation in your released code.

**Comment by walegahaha** [comment]
Sorry, I've updated the code in the targeted attack. We've improved the algorithm, here is the best.

**Comment by walegahaha** [comment]
> thx for releasing your code, but I have a question that in your paper, Whey Optimization is to divide noises into groups, I read your code roughly, I think your whey implementation is to divide into groups by pixel values 0 - 255, do I understand correctly?And I don't find the T1 pram settings. By the way, your whey step2, squeeze noises stochastically, I don't find the implementation in your released code.

Sorry, I've updated the code in the targeted attack. We've improved the algorithm in the grouping strategy.
